name: ci

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install pnpm (locked to v9 to match package.json)
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Setup Node + enable pnpm cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      # ---------- Quality gates ----------

      - name: Prettier
        run: pnpm prettier --check . --ignore-path .prettierignore

      - name: Lint
        run: pnpm eslint . --max-warnings=0 --ignore-path .eslintignore

      - name: Typecheck
        run: pnpm run typecheck

      - name: Tests
        run: pnpm run test:run

      # ---------- Coverage (generate lcov for optional Codecov) ----------
      - name: Tests (coverage)
        run: pnpm run test:coverage -- --coverage.reporter=lcov

      # ---------- Optional: upload to Codecov ----------
      # To enable:
      # 1) Add a repo secret: CODECOV_TOKEN
      # 2) Uncomment the step below
      #
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     files: ./coverage/lcov.info
      #     flags: unittests
      #     fail_ci_if_error: false
      #     token: ${{ secrets.CODECOV_TOKEN }}
