name: ci

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Let the action read the pinned version from package.json "packageManager"
      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Prettier
        run: pnpm prettier --check . --ignore-path .prettierignore

      - name: Lint
        run: pnpm eslint . --max-warnings=0 --ignore-path .eslintignore

      - name: Typecheck
        run: pnpm run typecheck

      - name: Tests
        run: pnpm run test:run

      - name: Tests (coverage)
        run: pnpm run test:coverage -- --coverage.reporter=lcov

      # Optional: add Codecov later by uncommenting and adding CODECOV_TOKEN secret
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     files: ./coverage/lcov.info
      #     flags: unittests
      #     fail_ci_if_error: false
      #     token: ${{ secrets.CODECOV_TOKEN }}
